version: '3'
services:
  backend:
    image: sunnam1607/yorokorom-backend:v2
    ports:
      - 8080:8080
    networks:
      - yorokorom-net

  frontend:
    image: sunnam1607/yorokorom-frontend:v2
    ports:
      - "80:80"
    networks:
      - yorokorom-net

networks:
  yorokorom-net:
    external: true
    driver: bridge
